### ISSUE TITLE
[bld] `examples` build tasks incorrectly search for the `confy` folder used for local dev

### ISSUE THREAD

**Issue by crystalthoughts** [heysokam/ngpu#1] opened 2023-12-08 09:41 UTC
Hi, when calling one of the tasks in the root directory (after nimble install) I get an unhandled exception:
For example after running `nimble buffer`:
```
Y:\Projects\Games\ngpu\confy.nims(4, 54) Error: cannot open file: ../confy/src/confy/nims
stack trace: (most recent call last)
C:\Users\Dan\AppData\Local\Temp\nimblecache-0\nimscriptapi_1534817442.nim(210, 16)
Y:\Projects\Games\ngpu\ngpu.nimble(34, 21) bufferTask
C:\Users\Dan\.choosenim\toolchains\nim-#devel\lib\system\nimscript.nim(263, 7) exec
C:\Users\Dan\.choosenim\toolchains\nim-#devel\lib\system\nimscript.nim(263, 7) Error: unhandled exception: FAILED: nim -d:cnimble confy.nims name [OSError]
nimscriptwrapper.nim(161) execScript
```

Any idea where I'm going wrong?

**Comment by heysokam** [comment] 2023-12-08 10:57
@crystalthoughts You are doing the right thing, but it seems like you found a leftover bug from the atlas+confy switch that got untested.
It is trying to erroneously find `confy` from my local dev folder, but that is incorrect because [this line](https://github.com/heysokam/ngpu/blob/9dd7b04943bf16f00c46bc4bcbbfcd2c23ec1213/confy.nims#L4) should be saying `when not defined(cnimble) ...etc` instead of `when not defined(nimble)`

The bug should only affect the examples, but let me know if it fails when using the library as a library from your own project for some reason.

I will make a quick commit to try and fix it, but I won't be able to test it until I have some free time, which will be around next month.

In the meantime, in case you find any other issues behind this one, you could also just ignore the confy buildsystem and build any of the examples with `nim c path/to/examples/file.nim` like usual in nim. The nimble tasks are there just for convenience.

**Comment by heysokam** [comment] 2023-12-08 11:04
#**TODO**: Confirm that this bug got fixed by https://github.com/heysokam/ngpu/commit/8fc0f2ab3c0c1f0ef7565637108bd53c5d7dcfd2

**Comment by crystalthoughts** [comment] 2023-12-13 12:59
Not sure if the problem is related , but now I get:
```
C:\Users\Daniel\.nimble\pkgs2\confy-0.1.11-5d7518bff8dbf059555320806296da1e439337fe\confy\nims.nim(89, 33)
C:\Users\Daniel\.nimble\pkgs2\confy-0.1.11-5d7518bff8dbf059555320806296da1e439337fe\confy\nims.nim(82, 97) asignOrFail
C:\Users\Daniel\.nimble\pkgs2\confy-0.1.11-5d7518bff8dbf059555320806296da1e439337fe\confy\nims.nim(82, 97) Error: unhandled exception: Tried to assign values for required variable packageName but none of the options are defined. [IOError]
stack trace: (most recent call last)
C:\Users\Daniel\AppData\Local\Temp\nimblecache-0\nimscriptapi_1054099271.nim(210, 16)
C:\Users\Daniel\Library\ngpu\ngpu.nimble(34, 21) bufferTask
C:\Users\Daniel\.choosenim\toolchains\nim-2.0.0\lib\system\nimscript.nim(265, 7) exec
C:\Users\Daniel\.choosenim\toolchains\nim-2.0.0\lib\system\nimscript.nim(265, 7) Error: unhandled exception: FAILED: nim -d:cnimble confy.nims name [OSError]
       Tip: 153 messages have been suppressed, use --verbose to show them.
nimscriptwrapper.nim(160) execScript

    Error:  Exception raised during nimble script execution
    ```

**Comment by crystalthoughts** [comment] 2023-12-13 13:13
I also have to hide nim.cfg in the examples folder for it to find the installed deps, after which I get `invalid pragma: winapi`.

**Comment by heysokam** [comment] 2023-12-14 13:47
> Not sure if the problem is related , but now after nimble buffer I get:

It is not related. This has happened before, but it is not `ngpu` related.
It is a `confy` error that triggers when confy cannot resolve the project's nimble file path correctly.
I never tested the examples on Windows, only on Linux and Mac, so that's probably why you found the errors. The seem to be leftovers from the confy+atlas switch I did a while ago.

Please try to build the examples without confy.
Each example file can be built by calling `nim c examples/thefile.nim` like normal nim building.


> I also have to hide nim.cfg in the examples folder for it to find the installed deps, after which I get `invalid pragma: winapi`

I do not use any winapi pragmas in any of my libraries. Are you sure this is not coming from your project in some way?
If you are only building the examples and you get this error, I would probably need a minimal reproduction example to debug what might be going on. Because I don't use winapi anywhere in my libraries, so I'm confused of why this exception is being thrown.

Are you using `confy` to build your project too, in conjuction with some other library that uses the `cpp` backend? If yes, then that would explain it, and it would be related to https://github.com/heysokam/confy/issues/3 because confy doesn't currently support building the nim-cpp backend until that feature is implemented.

If not, then I don't really know why this second one is being thrown.

In any case, these buildsystem bugs you found are definitely `confy` related.
Please build the examples manually with `nim c` while debugging and let me know what you find.

**Comment by crystalthoughts** [comment] 2023-12-14 15:17
Thanks for the info - 
I'm basically building in a clean pull of your project directly with `nim c examples/example_file.nim` as you suggest. Pretty much as clean as it could be. Those config files were throwing off the build chain so to a beginner (windows?) user of your project the same is likely to happen on first try. 

It's very likely I'm doing something else wrong as I'm a nim beginner but perhaps this is useful info for you. 

I'll try again when I have time and let you know what I find. I'll dig into where those pragmas are coming from and try it on another machine with the newest patch build of nim (this machine is running 2.0)

**Comment by heysokam** [comment] 2023-12-16 17:33
@crystalthoughts Yeah, it does help a lot. Nobody tested it on windows before, so it really helps knowing that there are still issues around.
And you are completely right that its currently not newbie-friendly because the buildsystem bugs are hard to solve. Normally you would just `nimble clear` or any other example, and it would just work, but the bug is getting in the way.

The `wgpu` wrapper that this library is based on was tested and works in all three systems, but I never got around testing `ngpu` outside of mac/linux.

I will try to debug it on a clean windows machine myself in about 3-4weeks if you haven't figured it out by then.

I'm usually more responsive, but I'm currently extremely busy with a new job. Until then, feel free to spam here with anything that comes up and I will try to give you a hand as I can.

**Comment by heysokam** [comment] 2023-12-23 06:00
@crystalthoughts This commit  https://github.com/heysokam/ngpu/commit/f8396b1311f95c0c6c88396429ddd2e92246c913 should fix your buildsystem issues
Can you confirm if it builds for you now?

**Comment by heysokam** [comment] 2023-12-25 15:46
@crystalthoughts
> I also have to hide nim.cfg in the examples folder for it to find the installed deps, after which I get `invalid pragma: winapi`. It might just be me being new to Nim, but could be worth testing in a clean environment ( it seems its looking for your locally installed libs by default for example)
The error was missing some context, and that really confused me.

I was able to reproduce this, and now I understand that this is happening because the wgpu buildsystem was never tested on windows, and it has a bug in how it is called.
![image](https://github.com/heysokam/ngpu/assets/7308253/15cd1b8a-a068-4386-a039-f8e8d62a769a)
It shouldn't be calling for `sh -c` to run cargo on windows, because that is an illegal operation on windows. Now that I see this I can remember that this was the very reason for which I didn't implement windows support right away, and left it as a todo for the future.


In any case, I have archived the wgpu wrapper, for the reasons mentioned in this link:
https://github.com/heysokam/wgpu#wgpu-wrapper-for-nim
I will be removing `wgpu-native` from this library entirely.
This is recent, after you opened this issue, and it is explained at the top of the readme file of this repository.
![image](https://github.com/heysokam/ngpu/assets/7308253/ad83b29a-7c58-4af8-972d-d64e408a7f02)

I will close this issue as `wont-fix`, but please continue the conversation here.
If you can give me some context on your reasons for using this library I will be able to recommend you a proper alternative for Nim.

**Closed by heysokam** 2023-12-25 15:46 UTC
Labels: bug

**Comment by crystalthoughts** [comment] 2023-12-25 18:15
Ah that's a shame. Could you use Nim itself to initiate a cross platform cmd execution? 
I moved to things like Nim in the hopes of escaping the various pitfalls of C++ , Python etc build/package management haha, guess it's a tough problem everywhere.

I was hoping to use your library as a graphics and games prototyping framework. A thin API over WebGPU and/or Vulkan is really what I've been looking for - the space is insanely fragmented and all of the complete projects are either lacking features/wrong backend (Raylib) seem incredibly bloated/very difficult to build successfully (the forge, bgfx etc)

Any advice welcome :)

**Comment by crystalthoughts** [comment] 2023-12-25 18:17
There's the very nice zig-gamedev for zig that works out of the box but the language is too fast-changing to build a large project around right now imo

**Comment by heysokam** [comment] 2023-12-25 18:30
> There's the very nice zig-gamedev for zig that works out of the box but the language is too fast-changing to build a large project around right now imo

Yeah for sure. I also tried zig-gamedev, but the lack of a proper package manager is a pain in the lang in general. And the new one is way too early in dev to be reliable.


> Could you use Nim itself to initiate a cross platform cmd execution?

Well that's the problem. The nim VM has no `execShellCmd`, although it should, and it is running commands in a really nitpicky way. So you have to implement platform-dependent execution if you want to run commands and also get their output back.


> I moved to things like Nim in the hopes of escaping the various pitfalls of C++ , Python etc build/package management haha, guess it's a tough problem everywhere.

Nah, this is just because you find the niche within the niche. This is usually not a problem at all in nim, but the wgpu bindings are a bit finicky, and wgpu itself changes a lot too. That's why you found this probl.

> I was hoping to use your library as a graphics and games prototyping framework. A thin API over WebGPU and/or Vulkan is really what I've been looking for 

Then your best bet right now is to follow the instructions that I left in the [recommended alternative for wgpu in nim](https://github.com/heysokam/wgpu#recommended-alternative).
It's already pretty much ready to use, but let me know if you have trouble with it.

I'm always on nim's discord, and tons of other knowledgeable people are around there too.
Feel free to @ me there, and ask either on #main or #gamedev if you get stuck.
Might be able to make a github gist with the setup to get you started if you cannot figure it out ✍️

**Comment by crystalthoughts** [comment] 2023-12-25 18:50
I'll play around with it, thanks for your help! Catch you on the discord

**Comment by crystalthoughts** [comment] 2023-12-25 18:52
(I might take you up on that gist but lets see how it goes in the ny)

**Comment by crystalthoughts** [comment] 2024-01-05 16:28
I have created a question on the Nim forums that will be relevant to the wgpu case. I'm struggling with the .dll case!
https://forum.nim-lang.org/t/10852#72329

Any help would be much appreciated

**Comment by heysokam** [comment] 2024-01-06 17:08
@crystalthoughts I see that PMunch already answered with a solution :)
I was going to say that the way to do things manually with dynamic linking looks similar to this setup found in many nim wrappers for libraries like vulkan, opengl or sdl2
https://github.com/nimgl/vulkan/blob/091ff99e6542f613aadb83c4aad7948299088d93/src/vulkan.nim#L11-L22

I'm glad that he did answer, because I was going to redirect you to him for dynamic linking, since I have only worked with static linking myself and have no exp with that type.

How is progress on the wgpu wrapper? Did you start with it yet?

**Comment by crystalthoughts** [comment] 2024-01-09 15:46
Thanks, I'll look into that too. 
Not had chance to dig into wrapping wgpu yet, but I'll let you know how I get on. I might try the sokol bindings first for some things, but I'll need compute shaders at some point.
